version: '2'

services:
  scripts.api:
    image: eeslp/scripts.api
    build:
      context: ./src/Services/Scripts.API
      dockerfile: Dockerfile
    depends_on:
      - mysql.data
      - redis.cache
    ports:
     - "5001:80"
    environment:
     - "Database:ConnectionString=Server=mysql.data;Port=3306;Database=EESLP;Uid=root;Pwd=supersecret"
     - "RabbitMq:Hostname=rabbit.eventbus"
     - "Services:redis.cache=redis.cache"
    entrypoint: dockerize -wait tcp://rabbit.eventbus:5672 -wait http://rabbit.eventbus:15672 -wait tcp://redis.cache:6379 -timeout 30s dotnet EESLP.Services.Scripts.API.dll
  logging.api:
    image: eeslp/logging.api
    build:
      context: ./src/Services/Logging.API
      dockerfile: Dockerfile
    depends_on:
      - mysql.data
      - redis.cache
      - scripts.api
    ports:
     - "5002:80"
    environment:
     - "Database:ConnectionString=Server=mysql.data;Port=3306;Database=EESLP;Uid=root;Pwd=supersecret"
     - "RabbitMq:Hostname=rabbit.eventbus"
     - "Services:redis.cache=redis.cache"
     - "Services:scripts.api=http://scripts.api"
    entrypoint: dockerize -wait tcp://rabbit.eventbus:5672 -wait http://rabbit.eventbus:15672 -wait tcp://redis.cache:6379 -timeout 30s dotnet EESLP.Services.Logging.API.dll
  frontend.gateway.api:
    image: eeslp/frontent.gateway.api
    build:
      context: ./src/Frontend/Gateway.API
      dockerfile: Dockerfile
    depends_on:
      - mysql.data
      - redis.cache
      - scripts.api
      - logging.api
    ports:
     - "5003:80"
    environment:
     - "Database:ConnectionString=Server=mysql.data;Port=3306;Database=EESLP;Uid=root;Pwd=supersecret"
     - "RabbitMq:Hostname=rabbit.eventbus"
     - "Services:redis.cache=redis.cache"
     - "Services:scripts.api=http://scripts.api"
     - "Services:logging.api=http://logging.api"
    entrypoint: dockerize -wait tcp://rabbit.eventbus:5672 -wait http://rabbit.eventbus:15672 -wait tcp://redis.cache:6379 -timeout 30s dotnet EESLP.Frontend.Gateway.API.dll
  frontend.ui:
    image: eeslp/frontend.ui
    build:
      context: ./src/Frontend/UI
      dockerfile: Dockerfile
    depends_on:
      - frontend.gateway.api
    ports:
      - "80:80"
    environment:
      - "ApiUrl=http://frontend.gateway.api/api/"
  mysql.data:
    image: eeslp/mysql.data
    environment: 
      MYSQL_DATABASE : EESLP
      MYSQL_ROOT_PASSWORD: supersecret
    build:
      context: ./src/Sql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
  rabbit.eventbus:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "ASDSGSKEDJLHXCAKGHJSC"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  redis.cache:
    image: redis
    ports:
      - "6379:6379"