CREATE TABLE IF NOT EXISTS `EESLP`.`Host` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Hostname` VARCHAR(50) NOT NULL,
  `FQDN` VARCHAR(250) NOT NULL,
  `ApiKey` VARCHAR(250) NOT NULL,
  `CreatedDateTime` DATETIME NULL,
  `LastModDateTime` DATETIME NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `FQDN_UNIQUE` (`FQDN` ASC),
  INDEX `ApiKey_INDEX` (`ApiKey` ASC))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `EESLP`.`Script` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Scriptname` VARCHAR(50) NOT NULL,
  `Description` TEXT NULL,
  `CreatedDateTime` DATETIME NULL,
  `LastModDateTime` DATETIME NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `ScriptName_UNIQUE` (`Scriptname` ASC))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `EESLP`.`ScriptInstance` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TransactionId` VARCHAR(150) NOT NULL,
  `HostId` INT NOT NULL,
  `ScriptId` INT NOT NULL,
  `InstanceStatus` VARCHAR(45) NOT NULL,
  `CreatedDateTime` DATETIME NOT NULL,
  `LastModDateTime` DATETIME NOT NULL,
  `EndDateTime` DATETIME NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC),
  INDEX `Status_INDEX` (`InstanceStatus` ASC))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `EESLP`.`Log` (
  `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ScriptInstanceId` INT UNSIGNED NOT NULL,
  `LogDateTime` DATETIME NOT NULL,
  `LogLevel` VARCHAR(45) NOT NULL,
  `LogText` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC),
  INDEX `Log_INDEX` (`LogLevel` ASC, `LogDateTime` ASC),
  FULLTEXT INDEX `LogText_FULLTEXT` (`LogText` ASC),
  INDEX `fk_Log_ScriptInstance_idx` (`ScriptInstanceId` ASC),
  CONSTRAINT `fk_Log_ScriptInstance`
    FOREIGN KEY (`ScriptInstanceId`)
    REFERENCES `EESLP`.`ScriptInstance` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;